### ISSUE TITLE
1.16.5 Crash on client

### ISSUE THREAD

**Issue by ghost** [pitbox46/HiddenNames#1]
Hi, i have strange problem. When i login on server with mod, i get crash.
Forge-1.16.5-36.1.16
Mod version latest
Here log

Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at github.pitbox46.hiddennames.HiddenNames.onNameFormat(HiddenNames.java:76) ~[?:1.16.5-1.1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_886_HiddenNames_onNameFormat_NameFormat.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2659/1800392465.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.getPlayerDisplayName(ForgeEventFactory.java:260) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_145748_c_(PlayerEntity.java:1757) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:transliterationlib.forge.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.PlayerInteractsEntityMixin,pl:mixin:APP:the_bumblezone.mixins.json:entities.PlayerTickMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.HoneyShieldDamageMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.HoneyShieldDisableMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.PlayerDamagedMixin,pl:mixin:APP:the_bumblezone.mixins.json:items.PlayerDamageShieldInvoker,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:ElytraPlayerMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:firstpersonmod.forge.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRenderer.func_225623_a_(EntityRenderer.java:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:performant.mixins.json:entity.EntityRendererFPSMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:216) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:obfuscate.mixins.json:client.OptifineLivingRendererMixin,pl:mixin:APP:firstpersonmod.forge.mixins.json:LivingEntityRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:64) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_225623_a_(PlayerRenderer.java:41) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:crossbows.2,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:renderer,pl:mixin:APP:notenoughcrashes.mixins.json:client.EntityRenderDispatcherMixin,pl:mixin:APP:firstpersonmod.forge.mixins.json:EntityRendererMangerMixin,pl:mixin:APP:quark.mixins.json:client.EntityRendererManagerMixin,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:2120) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.handler$zom000$render(WorldRenderer.java:8129) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1752) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:dungeons_gear.mixins.json:GameRendererMixin,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.modernui-forge.json:AccessGameRenderer,pl:mixin:APP:create.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:dungeons_gear.mixins.json:GameRendererMixin,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.modernui-forge.json:AccessGameRenderer,pl:mixin:APP:create.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.handler$zzh000$afterCrashHandled(Minecraft.java:2540) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/971497536.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

**Comment by pitbox46** [comment]
Do both the server and the client have the mod installed? And if you have access to the server logs they may also be helpful.

**Comment by ghost** [comment]
Hi, i have mod on server and client. Server logs is empty when i get crash, i look this many times. This error only client.

**Comment by pitbox46** [comment]
I am failing to recreate the issue. What other mods do you have?

**Comment by ghost** [comment]
Yes, Here list
Mod List: 
Create-stuff-additions1.16.5_v1.0.3.jar
Notenoughcrashes-3.1.8-forge.jar
Astralsorcery-1.16-1.16.5-1.13.12.jar
Supermartijn642configlib-1.0.6-mc1.16.jar
Justenoughbeacons-3.1-1.16.3.jar
NetherPortalFix_1.16.3-7.2.1.jar
TRansliterationLib-1.0.4.jar
Morecreatestuffs-mc1.16-b1.4.0.jar
AdditionalBanners-1.16.5-6.0.3.jar
Mcw-windows-1.0.3-mc1.16.5.jar
Rsgauges-1.16.4-1.2.10.jar
BlockArmor-1.16.5-2.6.2.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar
TerraForged-1.16.5-0.2.10.jar
CTM-MC1.16.1-1.1.2.6.jar
CookingForBlockheads_1.16.5-9.3.2.jar
YungsApi-1.16.4-Forge-6.jar
MutantBeasts-1.16.4-1.1.3.jar
Bookshelf-1.16.5-10.1.11.jar
Uncrafted-1.16-4.0.0pre1.jar
TvStudio-1.16.5v1.10.jar
Sophisticatedbackpacks-1.16.4-2.5.0.271.jar
Guardvillagers-1.16.5.1.2.4.jar
Mcw-doors-1.0.2-mc1.16.5.jar
MekanismGenerators-1.16.5-10.0.21.448.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
JustEnoughResources-1.16.3-0.12.0.100.jar
Shetiphiancore-1.16-3.8.5.jar
MmmMmmMmmMmm-1.16.5-1.2.0.jar
Twilightforest-1.16.5-4.0.490-universal.jar
Supplementaries-1.16.5-0.13.0.jar
Eleklib-1.16.5-1.4.1.jar
Betterendforge-1.16.4-1.6.0.jar
Chipped-1.0.6.1.jar
Createplus-1.16.4_v0.3.1.3.jar
TenshiLib-1.16.3-1.3.0.jar3.0        
Mcw-bridges-1.0.5-mc1.16.5-4.jar     
FarmersDelight-1.16.5-0.4.3.jar      
ResourcefulBees-1.16.5-0.6.7.2b.jar  
Blur-1.1.0-1.jar|1.1.0-1             
Drawerfps-1.9.jar1.9                 
Mcw-trapdoors-1.0.2-mc1.16.5.jar     
Mcw-fences-1.0.0-mc1.16.5.jar        
Supermartijn642corelib-1.0.3-mc1.16.5.jar
Fairylights-4.0.5-1.16.5.jar         
TrackAPI-1.16.4-forge-1.2.1.jar      
Curios-forge-1.16.5-4.0.5.1.jar      
Curious+Armor+Stands-1.16.5-2.1.0.jar
Patchouli-1.16.4-51.jar-51           
Сollective-1.16.5-2.25.jar           
Camera-1.16.5-1.0.6.jar-1.0.6        
Betterbiomeblend-1.16.4-1.1.4-forge.jar
TorchBandolier-1.16.3-1.5.1+11.jar   
Obfuscate-0.6.2-1.16.3.jar
EnigmaticLegacy-2.11.4.jar             
Buildersaddition-1.16.5-20210517a.jar   
Worldedit-mod-7.2.5-dist.jar    
MekanismTools-1.16.5-10.0.21.448.jar         
SpartanWeaponry-1.16.4-2.1.0-beta-4.jar       
Mcw-roofs-2.0.1-mc1.16.5-4.jar             
Cfm-7.0.0pre21-1.16.3.jar       
Morecfm-1.2.0-1.16.3.jar         
ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar
Cc-tweaked-1.16.4-1.95.3.jar  
Observerlib-1.16.4-1.5.1.jar
Productivebees-1.16.5-0.6.9.11.jar
ItemPhysic_v1.4.18_mc1.16.5.jar       
Trashcans-1.0.10-mc1.16.5.jar       
AdChimneys-1.16.4-6.0.10.0-build.0125.jar    
The_bumblezone-1.16.5-2.4.2.jar     
Smallships-1.16.5-1.8.5.jar           
ScalingHealth-1.16.5-4.1.1+7.jar           
CodeChickenLib-1.16.4-3.5.1.408-universal.jar
CleanView-1.16.5-v2.jar
DynamicTrees-1.16.5-0.10.0-Beta14.jar
DynamicTreesPlus-1.16.5-0.1.0-Beta8.jar 
Geckolib-forge-1.16.5-3.0.39.jar           
Corail_pillar-1.16-5.0.0.jar               
Dungeons_gear-1.16.5-3.0.16.jar             
QuarkOddities-1.16.3.jar              
inventorysorter-1.16.1-18.1.0.jar         
Mowziesmobs-1.5.17.jar              
Ae2wtlib-0.2-1.16.5.jar          
Cgm-1.0.1-1.16.3.jar              
Mining_helmet-1.16.5-2.0.1.jar               
Craftingstation-4.1.1.jar               
Spiders-2.0-1.16.4-1.0.4.jar               
Platforms-1.16-1.7.11.jar              
Jei-1.16.5-7.7.0.104.jar          
JustEnoughCalculation-1.16.5-3.6.6.jar             
Dungeons_mobs-1.16.5-1.0.5.jar              
Abnormals_core-1.16.5-3.1.1.jar               
Environmental-1.16.5-1.0.0.jar              
Buzzier_bees-1.16.5-3.0.1.jar              
Justmobheads_1.16.5-4.0.jar                 
Goblintraders-1.4.2-1.16.3.jar              
Mekanism-1.16.5-10.0.21.448.jar            
Caelus-forge-1.16.5-2.1.3.0.jar     
Colytra-forge-1.16.5-5.1.1.1.jar      
WAWLA-1.16.5-8.0.1.jar
Invtweaks-1.16.4-1.0.1.jar        
Create-mc1.16.5_v0.3.1c.jar
Waystones_1.16.5-7.6.2.jar            
WeaponThrow-1.16.4-4.2.jar        
Mcw-paintings-1.0.1-mc1.16.5.jar             
Clumps-6.0.0.24.jar            
Journeymap-1.16.5-5.7.2beta5.jar        
Comforts-forge-1.16.5-4.0.0.4.jar     
Appliedenergistics2-8.3.1.jar
TravelersBackpack-1.16.5-5.4.2.jar              
1.16.5-additionalbars-2.0.3.jar              
Framedcompactdrawers-1.16-2.2.0.jar         
Configured-1.0.2-1.16.3.jar              
OuterEnd-0.2.11.jar              
BotanyPots-1.16.5-7.0.17.jar
BotanyTrees-1.16.5-3.0.5.jar
AdHooks-1.16.4-6.1.5.0-build.0124.jar           
Snowundertrees-1.16.5-v1.1.4.jar          
Mcjtylib-1.16-5.0.18.jar        
Rftoolsbase-1.16-2.0.10.jar         
Xnet-1.16-3.0.13.jar       
Rftoolsstorage-1.16-2.0.12.jar        
Rftoolscontrol-1.16-4.0.10.jar        
Rftoolsdim-1.16-7.0.9-beta.jar   
Pedestals-0.8s_hotfix_3.jar      
Mapperbase-1.16.4-2.3.0.0.jar     
Roadstuff-1.16.4-4.2.0.jar       
Catalogue-1.2.1-1.16.5.jar          
EnderStorage-1.16.4-2.7.1.166-universal.jar
Ars_nouveau-1.16.5-1.18.2.jar           
Rftoolspower-1.16-3.0.8.jar         
ImmersivePetroleum-1.16.5-3.3.0-4.jar           
forge-1.16.5-36.1.16-universal.jar
DramaticDoors-1.16.3-1.1.0.jar    
WailaHarvestability-mc1.16.x-forge-1.1.15.jar           
Scuba-gear-1.16.5-1.0.3.jar           
Immersiveposts-1.16.5-4.1.0.jar
DynamicSurroundings-1.16.4-4.0.4.1.jar
Ironchest-1.16.4-11.2.10.jar
UniversalModCore-1.16.4-forge-1.0.1.jar            
ZeroCore2-1.16.4-2.0.21.jar       
ExtremeReactors2-1.16.4-2.0.23.jar      
forge-1.16.5-36.1.16-client.jar         
Upgrade_aquatic-1.16.5-3.1.0.jar           
Cofh_core-1.16.4-1.2.1.jar               
Thermal_foundation-1.16.4-1.2.0.jar              
Thermal_innovation-1.16.4-1.2.0.jar              
Thermal_expansion-1.16.4-1.2.0.jar              
Thermal_locomotion-1.16.4-1.2.0.jar            
Endergetic-1.16.4-3.0.0.jar               
Rftoolsutility-1.16-3.0.26.jar        
Woolplates-1.16.2-v1.2.1.jar            
EnchantmentDescriptions-1.16.5-7.0.8.jar
ToolBelt-1.16.5-1.16.0.jar            
ImmersiveEngineering-1.16.5-5.0.0-135.jar
Silent-lib-1.16.3-4.9.4+68.jar           
FirstPersonMod-2.0.1.jar             
CreativeCore_v2.1.3_mc1.16.5.jar               
ChickenChunks-1.16.4-2.7.0.85-universal.jar
Rftoolsbuilder-1.16-3.0.17.jar         
Jeiintegration_1.16.5-7.0.1.15.jar          
Justplayerheads_1.16.5-1.6.jar                
SpartanShields-1.16.5-2.1.2.jar            
Mantle-1.16.5-1.6.103.jar             
Inspirations-1.16.5-1.2.3.32.jar            
Pamhc2foodcore-1.16.3-1.0.2.jar       
Gravestone-1.16.5-1.0.6.jar      
Thermal_cultivation-1.16.4-1.2.0.jar             
Multibeds-1.16-1.7.9.jar              
AutoRegLib-1.6-49.jar             
AkashicTome-1.4-16.jar          
Quark-r2.4-312.jar          
DynamicTreesQuark-1.16.5-2.0.4.jar      
Extragolems-11.3.1.jar          
[1.16.5]+SecurityCraft+v1.8.21.1.jar        
StorageDrawers-1.16.3-8.2.2.jar             
Sit-1.16.2-v1.3.jar             
FluxNetworks-1.16.5-6.1.7.12.jar          
Performant-1.16.2-5-3.66m.jar             
Massunbind-1.16.5-1.1.jar         
InventoryHud_[1.16.2-1.16.5].forge-3.3.0.jar            
WorldEdit-CUI-FE3-1.16.5-3.0.9.jar            
Ferritecore-2.0.4-forge.jar
Engineersdecor-1.16.4-1.1.14-b2.jar
ModernUI-1.16.5-2.5.1.86-universal.jar
Farmerstea-1.16.5-1.2.jar       
Chiselsandbits-0.3.2-RELEASE.jar              
Morered-1.16.5-2.1.1.0.jar           
Сreateaddition-1.16.5-20210517a.jar  
DynamicTreesTerraForged-1.16.5-1.0.0.jar

**Comment by pitbox46** [comment]
Alright, I will look into what could be causing it. To make it easier on me, could you send me the modpack .zip or the .html file that has the links to the mods (If you're using the Curseforge launcher). You should be able to attach it directly to your comment.

**Comment by pitbox46** [comment]
Looking at the log, it looks like you have Optifine installed. I imagine that that is the conflict because Optifine messes with Minecraft's rendering. Try using the mod without it.

**Comment by ghost** [comment]
Ok, i test it soon and write here what result i get
